services:
  - type: web
    name: task-management
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: task-management-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://task-management.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 20

databases:
  - name: task-management-db
    plan: free
    postgresMajorVersion: 15